-- Permanent per-student Helping Bot conversation history.
-- Applied to the linked Supabase project on 2026-09-10.
CREATE TABLE IF NOT EXISTS public.helping_bot_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS helping_bot_messages_user_created_idx
    ON public.helping_bot_messages (user_id, created_at);
